# Generated by Django 4.2.6 on 2023-10-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
