# Generated by Django 4.2.5 on 2023-11-27 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
