# Generated by Django 4.2.5 on 2023-10-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_useraccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
