# Generated by Django 4.2.5 on 2023-12-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_premiummembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.premiummembership'),
        ),
    ]
