# Generated by Django 4.2.5 on 2023-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
