# Generated by Django 4.2.5 on 2023-12-05 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_validity_months_premiummembership_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.BooleanField(default=True)),
                ('payment_id', models.CharField(verbose_name='Payment ID')),
                ('order_id', models.CharField(verbose_name='Order ID')),
                ('signature', models.CharField(blank=True, null=True, verbose_name='Signature')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Premium_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
