# Generated by Django 4.2.5 on 2023-12-05 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workappreciation',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
