# Generated by Django 4.2.5 on 2023-12-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_rename_user_id_workappreciation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workappreciation',
            name='likes',
        ),
    ]
