# Generated by Django 4.2.5 on 2023-11-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.CharField(max_length=255, null=True)),
                ('work_caption', models.CharField(max_length=200)),
                ('is_valid', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Workimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_images/')),
                ('user_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.userwork')),
            ],
        ),
    ]
