# Generated by Django 4.2.5 on 2023-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_userconnection_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='account.userconnection'),
        ),
    ]
