# Generated by Django 4.2.5 on 2023-11-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userwork_workimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwork',
            old_name='user_id',
            new_name='user',
        ),
    ]
