# Generated by Django 4.2.5 on 2023-12-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_userconnection_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Premium_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='premium_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.premiummembership'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='premium',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.premiummembership'),
        ),
    ]
