# Generated by Django 4.2.5 on 2023-11-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_chatmessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
