# Generated by Django 4.2.5 on 2023-12-14 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_payment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='premium_selected',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.premiummembership'),
            preserve_default=False,
        ),
    ]
