# Generated by Django 4.2.5 on 2023-11-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_reciever_chatmessage_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='user_id',
        ),
    ]
