# Generated by Django 4.2.5 on 2023-12-14 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_payment_premium_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
    ]
