# Generated by Django 4.2.5 on 2023-12-14 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_payment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='premium_selected',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.premiummembership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
            preserve_default=False,
        ),
    ]
