# Generated by Django 4.2.5 on 2023-12-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_payment_premium_selected_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='premium_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.premiummembership'),
        ),
    ]
