# Generated by Django 4.2.5 on 2023-12-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_payment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='premium',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_member',
            field=models.BooleanField(default=False),
        ),
    ]
