# Generated by Django 4.2.5 on 2023-11-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_chatmessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwork',
            old_name='is_valid',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='account.useraccount'),
        ),
    ]
