# Generated by Django 4.2.5 on 2023-11-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_rename_is_valid_userwork_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workscomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('user_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_comments', to='account.userwork')),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='account.userconnection')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to='account.useraccount')),
            ],
        ),
    ]
